name: terraform-apply

on:
  push:
    branches: [main]

jobs:
  apply:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_PAGER: ""
    defaults:
      run:
        working-directory: terraform/app
    steps:
      - uses: actions/checkout@v4
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push multi-arch image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t "$ECR_REGISTRY/$ECR_REPOSITORY:latest" \
            --push .
      - name: Publish image digest to SSM
        env:
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: latest
          IMAGEDIGEST_SSM: ${{ secrets.IMAGEDIGEST_SSM }}
        run: |
          DIGEST=$(aws ecr describe-images --region "$AWS_REGION" --repository-name "$ECR_REPOSITORY" --image-ids imageTag=$IMAGE_TAG --query 'imageDetails[0].imageDigest' --output text)
          FULL_REF="$ECR_REGISTRY/$ECR_REPOSITORY@$DIGEST"
          aws ssm put-parameter --region "$AWS_REGION" --name "$IMAGEDIGEST_SSM" --type String --overwrite --value "$FULL_REF"
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.1
      - name: Terraform Init
        run: terraform init -input=false
      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
